server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: orderflow
    password: orderflow123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderEvent:com.orderflow.common.event.OrderEvent
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.orderflow.*
        spring.json.type.mapping: orderEvent:com.orderflow.common.event.OrderEvent,paymentEvent:com.orderflow.common.event.PaymentEvent,inventoryEvent:com.orderflow.common.event.InventoryEvent
      auto-offset-reset: earliest

jwt:
  secret: orderflow-secret-key-that-is-at-least-256-bits-long-for-hmac-sha
  expiration: 86400000

logging:
  level:
    com.orderflow: INFO
